# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets
import pyqtgraph as pg


class Ui_ULTRApy_Lite(object):
    def setupUi(self, ULTRApy_Lite):
        ULTRApy_Lite.setObjectName("ULTRApy_Lite")
        ULTRApy_Lite.resize(402, 538)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../old_ultrapy/Ultrapy/GUI/inmetro-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        ULTRApy_Lite.setWindowIcon(icon)

        self.verticalLayoutWidget_4 = QtWidgets.QWidget(ULTRApy_Lite)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 384, 521))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")

        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.image1 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.image1.setPixmap(QtGui.QPixmap('nesa grande icon.png'))
        self.horizontalLayout.addWidget(self.image1)

        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)

        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)

        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)

        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)

        self.horizontalLayout.addItem(spacerItem3)
        self.image2 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.image2.setPixmap(QtGui.QPixmap('icon_inmetro.png'))
        self.horizontalLayout.addWidget(self.image2)
        self.verticalLayout_4.addLayout(self.horizontalLayout)

        self.line = QtWidgets.QFrame(self.verticalLayoutWidget_4)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_7.addWidget(self.label_5)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_9.addWidget(self.label_4)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_9.addWidget(self.lineEdit_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_10.addWidget(self.label_8)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_10.addWidget(self.lineEdit_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_10)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setMouseTracking(False)
        self.lineEdit.setFrame(False)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_5.addWidget(self.lineEdit)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)

        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_11.addWidget(self.label_9)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_11.addWidget(self.lineEdit_5)
        self.horizontalLayout_3.addLayout(self.verticalLayout_11)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_6.addWidget(self.lineEdit_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_8.addWidget(self.label_7)
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        self.comboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_8.addWidget(self.comboBox)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)

        self.graph_widget = pg.PlotWidget(self.verticalLayoutWidget_4)
        self.graph_widget.setFixedWidth(383)
        self.graph_widget.setFixedHeight(250)
        self.graph_widget.setBackground('w')
        self.graph_widget.setLabel('left', 'Distance (m)', color='k')
        self.graph_widget.setLabel('bottom', 'Time (s)', color='k')
        # self.graph_widget.showGrid(x=True, y=True)
        axis_pen = pg.mkPen(color='black')
        self.graph_widget.getAxis('bottom').setPen(axis_pen)
        self.graph_widget.getAxis('left').setPen(axis_pen)
        self.verticalLayout_2.addWidget(self.graph_widget)

        self.line_3 = QtWidgets.QFrame(self.verticalLayoutWidget_4)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)

        self.pushButton2 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton2.setObjectName("pushButton2")
        self.horizontalLayout_2.addWidget(self.pushButton2)

        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)

        self.retranslateUi(ULTRApy_Lite)
        QtCore.QMetaObject.connectSlotsByName(ULTRApy_Lite)

    def retranslateUi(self, ULTRApy_Lite):
        _translate = QtCore.QCoreApplication.translate
        ULTRApy_Lite.setWindowTitle(_translate("ULTRApy_Lite", "ULTRApy_Lite"))
        self.label.setText(_translate("ULTRApy_Lite", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">ULTRApy</span></p></body></html>"))
        self.label_2.setText(_translate("ULTRApy_Lite", "<html><head/><body><p align=\"right\">Lite</p></body></html>"))
        self.label_7.setText(
            _translate("ULTRApy_Lite", "<html><head/><body><p align=\"center\">Gain</p></body></html>"))
        self.comboBox.setItemText(1, _translate("ULTRApy_Lite", "0.6"))
        self.comboBox.setItemText(2, _translate("ULTRApy_Lite", "1.8"))
        self.comboBox.setItemText(3, _translate("ULTRApy_Lite", "5.5"))
        self.comboBox.setItemText(4, _translate("ULTRApy_Lite", "12.9"))
        self.comboBox.setItemText(5, _translate("ULTRApy_Lite", "30.2"))
        self.comboBox.setItemText(6, _translate("ULTRApy_Lite", "66.1"))
        self.comboBox.setItemText(7, _translate("ULTRApy_Lite", "144"))
        self.label_5.setText(
            _translate("ULTRApy_Lite", "<html><head/><body><p align=\"center\">Set Range [mm]</p></body></html>"))
        self.label_4.setText(_translate("ULTRApy_Lite", "<html><head/><body><p align=\"center\">Min</p></body></html>"))
        self.lineEdit_3.setText(_translate("ULTRApy_Lite", "400"))
        self.label_8.setText(_translate("ULTRApy_Lite", "<html><head/><body><p align=\"center\">Max</p></body></html>"))
        self.lineEdit_4.setText(_translate("ULTRApy_Lite", "2000"))
        self.label_9.setText(
            _translate("ULTRApy_Lite", "<html><head/><body><p align=\"center\">Device path</p></body></html>"))
        self.lineEdit_5.setText(_translate("ULTRApy_Lite", "/dev/ttyUSB0"))

        self.label_6.setText(_translate("ULTRApy_Lite",
                                        "<html><head/><body><p align=\"center\">Water wave velocity [m/s]</p></body></html>"))
        self.lineEdit_2.setText(_translate("ULTRApy_Lite", "1480"))
        self.label_3.setText(_translate("ULTRApy_Lite",
                                        "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Distance [mm]</span></p></body></html>"))

        self.pushButton.setText(_translate("ULTRApy_Lite", "Acquire"))
        self.pushButton2.setText(_translate("ULTRApy_Lite", "Resume"))
